"""empty message

Revision ID: 0d71d5592a19
Revises: 92c7218d20ef
Create Date: 2022-06-03 19:01:36.372338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d71d5592a19'
down_revision = '92c7218d20ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('venues', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('artists', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
